-- cryptobot schema (SQL Server 2025 Express)
-- Run via sqlcmd or SSMS. GO is a batch separator (not SQL).
-- Idempotency: the CREATE DATABASE step is guarded; table CREATEs are not,
-- so drop tables manually if you need to re-apply against an existing DB.

IF DB_ID('cryptobot') IS NULL
    CREATE DATABASE cryptobot;
GO

USE cryptobot;
GO

-- 1. Historical OHLCV bars
CREATE TABLE market_data (
    id              BIGINT IDENTITY(1,1) PRIMARY KEY,
    symbol          VARCHAR(20)    NOT NULL,
    timeframe       VARCHAR(10)    NOT NULL,   -- '4Hour', '1Day'
    ts              DATETIME2(0)   NOT NULL,   -- UTC bar start time
    open_px         DECIMAL(20,8)  NOT NULL,
    high_px         DECIMAL(20,8)  NOT NULL,
    low_px          DECIMAL(20,8)  NOT NULL,
    close_px        DECIMAL(20,8)  NOT NULL,
    volume          DECIMAL(28,8)  NOT NULL,
    trade_count     INT            NULL,
    vwap            DECIMAL(20,8)  NULL,
    created_at      DATETIME2(3)   DEFAULT SYSUTCDATETIME(),
    CONSTRAINT uq_market_data UNIQUE (symbol, timeframe, ts)
);
CREATE INDEX ix_market_data_sym_tf_ts ON market_data(symbol, timeframe, ts DESC);
GO

-- 2. Signals generated by the strategy
CREATE TABLE signals (
    id              BIGINT IDENTITY(1,1) PRIMARY KEY,
    ts              DATETIME2(3)   NOT NULL DEFAULT SYSUTCDATETIME(),
    symbol          VARCHAR(20)    NOT NULL,
    strategy        VARCHAR(50)    NOT NULL,   -- 'donchian_20_10'
    side            VARCHAR(5)     NOT NULL,   -- 'BUY' | 'SELL'
    signal_price    DECIMAL(20,8)  NOT NULL,
    atr             DECIMAL(20,8)  NULL,
    proposed_qty    DECIMAL(28,8)  NULL,
    proposed_stop   DECIMAL(20,8)  NULL,
    notes           NVARCHAR(500)  NULL
);
CREATE INDEX ix_signals_ts ON signals(ts DESC);
GO

-- 3. Orders sent to Alpaca
CREATE TABLE orders (
    id                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    client_order_id     VARCHAR(64)    NOT NULL UNIQUE,
    alpaca_order_id     VARCHAR(64)    NULL,
    signal_id           BIGINT         NULL FOREIGN KEY REFERENCES signals(id),
    symbol              VARCHAR(20)    NOT NULL,
    side                VARCHAR(5)     NOT NULL,
    type                VARCHAR(20)    NOT NULL,   -- 'market', 'limit', 'stop_limit'
    qty                 DECIMAL(28,8)  NOT NULL,
    limit_price         DECIMAL(20,8)  NULL,
    status              VARCHAR(20)    NOT NULL,   -- 'new','filled','canceled','rejected'
    submitted_at        DATETIME2(3)   NOT NULL DEFAULT SYSUTCDATETIME(),
    filled_qty          DECIMAL(28,8)  NULL,
    filled_avg_price    DECIMAL(20,8)  NULL,
    filled_at           DATETIME2(3)   NULL,
    raw_response        NVARCHAR(MAX)  NULL
);
CREATE INDEX ix_orders_status_ts ON orders(status, submitted_at DESC);
GO

-- 4. Filled trades / round-trip P&L
CREATE TABLE trades (
    id              BIGINT IDENTITY(1,1) PRIMARY KEY,
    symbol          VARCHAR(20)    NOT NULL,
    entry_order_id  BIGINT         FOREIGN KEY REFERENCES orders(id),
    exit_order_id   BIGINT         FOREIGN KEY REFERENCES orders(id),
    entry_ts        DATETIME2(3)   NOT NULL,
    exit_ts         DATETIME2(3)   NULL,
    entry_price     DECIMAL(20,8)  NOT NULL,
    exit_price      DECIMAL(20,8)  NULL,
    qty             DECIMAL(28,8)  NOT NULL,
    pnl_usd         DECIMAL(20,8)  NULL,
    pnl_pct         DECIMAL(10,4)  NULL,
    fees_usd        DECIMAL(20,8)  NULL,
    status          VARCHAR(10)    NOT NULL DEFAULT 'OPEN' -- OPEN | CLOSED
);
CREATE INDEX ix_trades_status ON trades(status);
GO

-- 5. Currently open positions (mirror of Alpaca)
CREATE TABLE positions (
    symbol          VARCHAR(20)    PRIMARY KEY,
    qty             DECIMAL(28,8)  NOT NULL,
    avg_entry_price DECIMAL(20,8)  NOT NULL,
    current_stop    DECIMAL(20,8)  NULL,
    opened_at       DATETIME2(3)   NOT NULL,
    last_updated    DATETIME2(3)   NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

-- 6. Daily account equity snapshots
CREATE TABLE account_snapshots (
    id              BIGINT IDENTITY(1,1) PRIMARY KEY,
    ts              DATETIME2(0)   NOT NULL DEFAULT SYSUTCDATETIME(),
    equity          DECIMAL(20,2)  NOT NULL,
    cash            DECIMAL(20,2)  NOT NULL,
    buying_power    DECIMAL(20,2)  NOT NULL,
    portfolio_value DECIMAL(20,2)  NOT NULL
);
CREATE INDEX ix_snap_ts ON account_snapshots(ts DESC);
GO

-- 7. Bot operational logs (errors and key events)
CREATE TABLE logs (
    id          BIGINT IDENTITY(1,1) PRIMARY KEY,
    ts          DATETIME2(3)   NOT NULL DEFAULT SYSUTCDATETIME(),
    level       VARCHAR(10)    NOT NULL,    -- INFO/WARN/ERROR
    module      VARCHAR(50)    NULL,
    message     NVARCHAR(MAX)  NOT NULL,
    exception   NVARCHAR(MAX)  NULL
);
CREATE INDEX ix_logs_ts_lvl ON logs(ts DESC, level);
GO
